name: Deploy to Vercel

on:
  push:
    branches:
      - main # Replace with your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Vercel CLI
      run: npm i -g vercel

    - name: Deploy to Vercel
      run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm
